#ifndef TEXTDETECTOREAST_GLOBAL_H
#define TEXTDETECTOREAST_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TEXTDETECTOREAST_LIBRARY)
#  define TEXTDETECTOREASTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TEXTDETECTOREASTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TEXTDETECTOREAST_GLOBAL_H
